import { mkdir, stat, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { Constants, EdgeTTS } from '@andresaya/edge-tts';
import { HANGUL_GROUPS } from '../../src/app/hangul/data/hangul-groups';

const OUTPUT_DIR = '../../src/assets/audio/hangul';
const GENERATED_AUDIO_MAP_PATH =
  '../../src/app/hangul/data/generated/hangul-audio.generated.ts';

const AUDIO_SRC_PREFIX = 'assets/audio/hangul';

const VOICE = 'ko-KR-SunHiNeural';

const OUTPUT_FORMAT = Constants.OUTPUT_FORMAT.AUDIO_24KHZ_48KBITRATE_MONO_MP3;

interface AudioJob {
  id: string;
  text: string;
  outputBasePath: string;
  outputFilePath: string;
  audioSrc: string;
}

async function main(): Promise<void> {
  await mkdir(OUTPUT_DIR, { recursive: true });

  const jobs = getAudioJobs();

  console.log(`Generating ${jobs.length} Hangul audio files...`);

  let created = 0;
  let skipped = 0;
  let failed = 0;

  const completedJobs: AudioJob[] = [];

  for (const job of jobs) {
    if (await fileExists(job.outputFilePath)) {
      skipped++;
      completedJobs.push(job);
      console.log(`skip    ${job.id} → ${job.outputFilePath}`);
      continue;
    }

    try {
      const tts = new EdgeTTS();

      await tts.synthesize(job.text, VOICE, {
        rate: '-15%',
        pitch: '+0Hz',
        volume: '100%',
        outputFormat: OUTPUT_FORMAT,
      });

      const savedPath = await tts.toFile(job.outputBasePath);

      created++;
      completedJobs.push(job);
      console.log(`created ${job.id} → ${savedPath}`);
    } catch (error) {
      failed++;
      console.error(`failed  ${job.id} (${job.text})`, error);
    }
  }

  await writeGeneratedAudioMap(completedJobs);

  console.log('');
  console.log(`Done.`);
  console.log(`Created: ${created}`);
  console.log(`Skipped: ${skipped}`);
  console.log(`Failed:  ${failed}`);
  console.log(`Audio map: ${GENERATED_AUDIO_MAP_PATH}`);

  if (failed > 0) {
    process.exitCode = 1;
  }
}

function getAudioJobs(): AudioJob[] {
  const seen = new Set<string>();
  const jobs: AudioJob[] = [];

  for (const group of HANGUL_GROUPS) {
    for (const item of group.items) {
      if (seen.has(item.id)) {
        continue;
      }

      seen.add(item.id);

      const audioSrc = `${AUDIO_SRC_PREFIX}/${item.id}.mp3`;
      const outputBasePath = join(OUTPUT_DIR, item.id);
      const outputFilePath = `${outputBasePath}.mp3`;

      jobs.push({
        id: item.id,
        text: item.hangul,
        outputBasePath,
        outputFilePath,
        audioSrc,
      });
    }
  }

  return jobs;
}

async function writeGeneratedAudioMap(jobs: AudioJob[]): Promise<void> {
  await mkdir(dirname(GENERATED_AUDIO_MAP_PATH), { recursive: true });

  const uniqueJobs = [...jobs].sort((a, b) => a.id.localeCompare(b.id));

  const entries = uniqueJobs
    .map(job => `  ${JSON.stringify(job.id)}: ${JSON.stringify(job.audioSrc)},`)
    .join('\n');

  const contents = `// This file is generated by tools/hangul-audio/generate-hangul-audio.ts.
// Do not edit manually.

export const HANGUL_AUDIO_SRC_BY_ID: Record<string, string> = {
${entries}
};
`;

  await writeFile(GENERATED_AUDIO_MAP_PATH, contents, 'utf8');
}

async function fileExists(path: string): Promise<boolean> {
  try {
    const result = await stat(path);
    return result.isFile();
  } catch {
    return false;
  }
}

main().catch(error => {
  console.error(error);
  process.exit(1);
});